from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict


@dataclass
class Event:
    type: str
    payload: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


class EventTypes:
    APP_STARTED = "APP_STARTED"
    APP_READY = "APP_READY"
    APP_STOPPING = "APP_STOPPING"
    APP_STOPPED = "APP_STOPPED"
    SERVICE_REGISTERED = "SERVICE_REGISTERED"
    SERVICE_INITIALIZING = "SERVICE_INITIALIZING"
    SERVICE_STARTED = "SERVICE_STARTED"
    SERVICE_READY = "SERVICE_READY"
    SERVICE_BUSY = "SERVICE_BUSY"
    SERVICE_DEGRADED = "SERVICE_DEGRADED"
    SERVICE_FAILED = "SERVICE_FAILED"
    SERVICE_STOPPED = "SERVICE_STOPPED"
    SERVICE_RECOVERING = "SERVICE_RECOVERING"
    SERVICE_RECOVERED = "SERVICE_RECOVERED"
    
    RUNTIME_UPDATE = "RUNTIME_UPDATE"

    CONFIG_LOADED = "CONFIG_LOADED"

    # Enrollment Events
    ENROLLMENT_RECORDING_STARTED = "ENROLLMENT_RECORDING_STARTED"
    ENROLLMENT_SPEECH_DETECTED = "ENROLLMENT_SPEECH_DETECTED"
    ENROLLMENT_SAMPLE_ACCEPTED = "ENROLLMENT_SAMPLE_ACCEPTED"
    ENROLLMENT_SAMPLE_REJECTED = "ENROLLMENT_SAMPLE_REJECTED"
    ENROLLMENT_NEXT_PHRASE = "ENROLLMENT_NEXT_PHRASE"
    ENROLLMENT_PROGRESS_UPDATED = "ENROLLMENT_PROGRESS_UPDATED"

    # Owner Events
    OWNER_PROFILE_CREATED = "OWNER_PROFILE_CREATED"
    OWNER_VERIFIED = "OWNER_VERIFIED"
    OWNER_READY = "OWNER_READY"
    OWNER_VERIFICATION_FAILED = "OWNER_VERIFICATION_FAILED"

    # Conversation Events
    CONVERSATION_STARTED = "CONVERSATION_STARTED"
    WAKEWORD_DETECTED = "WAKEWORD_DETECTED"
    SPEAKER_VERIFICATION_STARTED = "SPEAKER_VERIFICATION_STARTED"
    SPEAKER_VERIFIED = "SPEAKER_VERIFIED"
    SPEAKER_REJECTED = "SPEAKER_REJECTED"
    LISTENING_STARTED = "LISTENING_STARTED"
    LISTENING_STOPPED = "LISTENING_STOPPED"
    TRANSCRIPTION_STARTED = "TRANSCRIPTION_STARTED"
    TRANSCRIPTION_COMPLETED = "TRANSCRIPTION_COMPLETED"
    AI_PROCESSING_STARTED = "AI_PROCESSING_STARTED"
    AI_PROCESSING_COMPLETED = "AI_PROCESSING_COMPLETED"
    RESPONSE_GENERATION_STARTED = "RESPONSE_GENERATION_STARTED"
    RESPONSE_GENERATION_COMPLETED = "RESPONSE_GENERATION_COMPLETED"
    SPEAKING_STARTED = "SPEAKING_STARTED"
    SPEAKING_COMPLETED = "SPEAKING_COMPLETED"
    CONVERSATION_INTERRUPTED = "CONVERSATION_INTERRUPTED"
    CONVERSATION_TIMEOUT = "CONVERSATION_TIMEOUT"
    CONVERSATION_FAILED = "CONVERSATION_FAILED"
    CONVERSATION_COMPLETED = "CONVERSATION_COMPLETED"
